### ISSUE TITLE
when navigating between pages throw the search bar while signed in goes wrong (should work properly when signed un)

### ISSUE THREAD

**Issue by rakad-kh** [WebAhead7/dr-workout-app#8]
<img width="1338" alt="Screen Shot 2020-11-26 at 14 30 39" src="https://user-images.githubusercontent.com/69585198/100351340-f8a42f00-2ff3-11eb-9fed-3e9337faef07.png">

**Comment by ahmad420** [comment]
I think the problem is with the hosting Netlify server.
you can clone the repo and check there, it works perfectly.
